// swift-tools-version: 5.9
import PackageDescription

// This Package.swift exists primarily so QA can build the shared core and run
// the parser test suite from the command line (`swift build`, `swift test`).
//
// The shippable product — including the WidgetKit extension and App Group —
// is built from the Xcode project (`Claudemon.xcodeproj`, generated by
// XcodeGen from `project.yml`). See scripts/build-xcode.sh.
let package = Package(
    name: "Claudemon",
    platforms: [
        .macOS(.v14)
    ],
    targets: [
        // Shared, network-free model + parsing + cache, used by app and widget.
        .target(
            name: "ClaudemonCore",
            path: "Sources/ClaudemonCore"
        ),
        // The menu-bar app target (links ClaudemonCore).
        .executableTarget(
            name: "Claudemon",
            dependencies: ["ClaudemonCore"],
            path: "Sources/Claudemon"
        ),
        // Parser/model tests, plus launch-priming tests for the app's UsageStore.
        .testTarget(
            name: "ClaudemonTests",
            dependencies: ["ClaudemonCore", "Claudemon"],
            path: "Tests/ClaudemonTests"
        )
    ]
)
